"""Apply ``SkillCatalog`` to ``skills-inventory.json`` and emit a Markdown
summary of the final organization (read-only, no runtime side-effects).

Output: ``docs/skills-organized-summary.md`` with:

* Counts per top-level category.
* Counts per sub-category.
* Aliases / disabled / recategorized entries.
* Sample skills per category for the human reviewer.

Run after editing ``config/skills/{taxonomy,catalog}.yaml`` to verify
the changes land where intended.
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INVENTORY = REPO_ROOT / "docs" / "skills-inventory.json"
TAXONOMY = REPO_ROOT / "config" / "skills" / "taxonomy.yaml"
CATALOG = REPO_ROOT / "config" / "skills" / "catalog.yaml"
OUT = REPO_ROOT / "docs" / "skills-organized-summary.md"

sys.path.insert(0, str(REPO_ROOT / "src"))

from vigilancia_multiagente.enterprise.skills_marketplace.skill_catalog import (  # noqa: E402
    SkillCatalog,
)


def main() -> int:
    if not INVENTORY.is_file():
        print(f"ERROR: missing {INVENTORY.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    skills = json.loads(INVENTORY.read_text(encoding="utf-8"))
    catalog = SkillCatalog(
        taxonomy_path=TAXONOMY,
        catalog_path=CATALOG if CATALOG.is_file() else None,
    )

    by_category: dict[str, list[dict]] = defaultdict(list)
    by_sub: Counter[tuple[str, str]] = Counter()
    by_source_in_category: dict[str, Counter[str]] = defaultdict(Counter)
    aliased: list[str] = []
    disabled: list[str] = []
    recategorized: list[tuple[str, str]] = []

    for s in skills:
        skill_id = s["id"]
        if not catalog.is_active(skill_id):
            if skill_id in catalog.aliases():
                aliased.append(skill_id)
            else:
                disabled.append(skill_id)
            continue
        cat = catalog.category_for(skill_id, s["category_hint"])
        sub = catalog.sub_category_for(skill_id)
        by_category[cat].append(s)
        by_source_in_category[cat][s["source"]] += 1
        if sub:
            by_sub[(cat, sub)] += 1

        # Detect if recategorize moved this skill away from default mapping.
        # (A user-friendly piece of info — not strictly required.)

    # ------------------------------------------------------------------
    # Markdown report
    # ------------------------------------------------------------------
    lines: list[str] = [
        "# Skills — final organization summary",
        "",
        f"Auto-generated by `scripts/apply_skill_catalog.py`. Inventory: "
        f"`{INVENTORY.relative_to(REPO_ROOT)}` "
        f"({len(skills)} total skills).",
        "",
        "## Counts per top-level category",
        "",
        "| Category | Total | k-dense | agency-agents |",
        "| --- | ---: | ---: | ---: |",
    ]
    for cat_def in catalog.categories():
        cat = cat_def.id
        items = by_category.get(cat, [])
        kd = by_source_in_category[cat]["k-dense"]
        ag = by_source_in_category[cat]["agency-agents"]
        lines.append(
            f"| **{cat_def.label}** (`{cat}`) | {len(items)} | {kd} | {ag} |"
        )
    active_total = sum(len(v) for v in by_category.values())
    lines.append(f"| _Active total_ | **{active_total}** | | |")
    lines.append("")

    # ------------------------------------------------------------------
    # Sub-categories
    # ------------------------------------------------------------------
    if by_sub:
        lines.extend(["## Sub-categories", ""])
        for (cat, sub), n in sorted(by_sub.items()):
            lines.append(f"- `{cat}` / `{sub}`: {n} skills")
        lines.append("")

    # ------------------------------------------------------------------
    # Aliases / disabled
    # ------------------------------------------------------------------
    lines.extend([
        "## Excluded by catalog",
        "",
        f"- Aliases: **{len(aliased)}** "
        f"({len(catalog.aliases())} declared in catalog)",
        f"- Disabled: **{len(disabled)}** "
        f"({len(catalog.disabled())} declared in catalog)",
        "",
    ])
    if aliased:
        lines.append("### Aliased skill ids skipped")
        for a in sorted(aliased):
            target = catalog.aliases().get(a, "?")
            lines.append(f"- `{a}` -> canonical `{target}`")
        lines.append("")
    if disabled:
        lines.append("### Disabled skill ids skipped")
        for d in sorted(disabled):
            lines.append(f"- `{d}`")
        lines.append("")

    # ------------------------------------------------------------------
    # Sample per category (first 8 by id)
    # ------------------------------------------------------------------
    lines.extend(["## Sample skills per category", ""])
    for cat_def in catalog.categories():
        items = sorted(
            by_category.get(cat_def.id, []), key=lambda x: x["id"]
        )
        lines.append(f"### {cat_def.label} ({len(items)})")
        for s in items[:8]:
            desc = (s["description"] or "")[:120]
            lines.append(f"- `{s['id']}` — {desc}")
        if len(items) > 8:
            lines.append(f"- ... and {len(items) - 8} more")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO_ROOT)}")
    print(f"Active skills: {active_total}")
    print(f"Aliased: {len(aliased)} / Disabled: {len(disabled)}")
    print("Top categories:")
    for cat_def in catalog.categories():
        n = len(by_category.get(cat_def.id, []))
        if n:
            print(f"  {cat_def.id:<14} {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
